---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zesming.
--- DateTime: 2021/9/18 23:00
---

local modName = ...;
local iconCutoff = 6
local iconPath = "Interface\\GLUES\\CHARACTERCREATE\\UI-CharacterCreate-Classes" -- Classes icon path

bb = CreateFrame("Frame",modName,UIParent,BackdropTemplateMixin and "BackdropTemplate");	-- 9.0.1: Using BackdropTemplate
bb.items = {}
bb.gearItems = {}
bb.classItems = {}
bb.showedClassTitle = {}
bb.selectedClass = {}

--------------------------------------------------------------------------------------------------------
--                                           Helper                                                   --
--------------------------------------------------------------------------------------------------------

local function resetContainer()
    if #bb.gearItems ~= 0 then
        for i = 1, #bb.gearItems do
            bb.gearItems[i]:Hide()
        end
        bb.gearItems = {}
    end
end

local function iconOffset(col, row)
    local offsetString = (col * 64 + iconCutoff) .. ":" .. ((col + 1) * 64 - iconCutoff)
    return offsetString .. ":" .. (row * 64 + iconCutoff) .. ":" .. ((row + 1) * 64 - iconCutoff)
end

--------------------------------------------------------------------------------------------------------
--                                           Build UI                                                 --
--------------------------------------------------------------------------------------------------------

local function gearItem(itemID, index)
    local itemName, itemLink, itemRarity, itemLevel, itemMinLevel, itemType, itemSubType, itemStackCount, itemEquipLoc, itemTexture, itemSellPrice = GetItemInfo(itemID)
    local gearText = itemLink
    if itemEquipLoc and itemRarity then
        local _, _, _, hex = GetItemQualityColor(itemRarity)
        local localizedLoc = _G[itemEquipLoc]
        if not localizedLoc then
            localizedLoc = itemSubType
        end
        gearText = '|c'.. hex .. '[' .. 'Lv.' .. itemLevel .. '|' .. localizedLoc .. '|' .. itemName .. ']'
    end

    -- Item
    local item = CreateFrame("Frame", nil, bb.container, BackdropTemplateMixin and "BackdropTemplate")
    item:SetBackdrop({ bgFile = "", edgeFile = "", edgeSize = 0, insets = { left = 3, right = 3, top = 3, bottom = 3 } });
    item:SetBackdropColor(0,0,0,0)

    local gearItemIcon = item:CreateTexture()
    gearItemIcon:SetTexture(itemTexture)
    gearItemIcon:SetPoint("TOPLEFT")

    local gearItemString = item:CreateFontString(nil,"ARTWORK","GameFontHighlight");
    gearItemString:SetPoint("TOPLEFT", gearItemIcon, "TOPRIGHT", 2, 0)
    gearItemString:SetFont(gearItemString:GetFont(),16,"THICKOUTLINE");
    gearItemString:SetText(gearText)

    item:SetSize(gearItemString:GetWidth(), gearItemString:GetHeight())
    gearItemIcon:SetSize(gearItemString:GetHeight(), gearItemString:GetHeight())
    SetPortraitToTexture(gearItemIcon, "player")

    if (index == 1) then
        item:SetPoint("TOPLEFT", bb.showedClassTitle[1], "BOTTOMLEFT",12, -8)
    else
        item:SetPoint("TOPLEFT",bb.gearItems[#bb.gearItems], "BOTTOMLEFT", 0, -4)
    end

    item:SetScript("OnEnter", function()
        if (itemLink) then
            GameTooltip:SetOwner(gearItemString, "ANCHOR_TOP")
            GameTooltip:SetHyperlink(itemLink)
            GameTooltip:Show()
        end
    end)

    item:SetScript("OnLeave", function()
        GameTooltip:Hide()
    end)

    bb.gearItems[index] = item
end

local function gearList(items)
    resetContainer()
    if items then
        for i = 1, #items do
            gearItem(items[i].ID, i)
        end
    end
end

local function itemsTitle(classInfo)
    bb.selectedClass = classInfo
    if #bb.showedClassTitle ~= 0 then
        bb.showedClassTitle[1]:Hide()
        bb.showedClassTitle = {}
        resetContainer()
    end
    local class = classInfo.class
    local spec = classInfo.spec
    local c = class:upper()
    local color = RAID_CLASS_COLORS[c]
    local coords = CLASS_ICON_TCOORDS[c]
    local classIconString = "|T" .. iconPath .. ":14:14:::256:256:" .. iconOffset(coords[1] * 4, coords[3] * 4) .. "|t"

    local item = CreateFrame("Frame", nil, bb.container, BackdropTemplateMixin and "BackdropTemplate")
    item:SetBackdrop({ bgFile = "", edgeFile = "", edgeSize = 0, insets = { left = 3, right = 3, top = 3, bottom = 3 } });
    item:SetBackdropColor(0,0,0,0)

    local classString = item:CreateFontString(nil,"ARTWORK","GameFontHighlight");
    classString:SetPoint("TOPLEFT")
    classString:SetFont(classString:GetFont(),16,"THICKOUTLINE");
    classString:SetText(classIconString .. " " .. class .. " " .. spec)
    classString:SetTextColor(color.r, color.g, color.b)

    local phaseButtons = {}
    for i = 1, 5 do
        local phaseButton = CreateFrame("Button", "TauntingButton", item, "UIPanelButtonTemplate")
        local phaseString = phaseButton:CreateFontString(nil,"ARTWORK","GameFontHighlight");
        phaseString:SetPoint("LEFT")
        phaseString:SetPoint("RIGHT")
        phaseString:SetFont(phaseString:GetFont(),12,"THICKOUTLINE");
        phaseString:SetJustifyH("CENTER")
        phaseString:SetText("P".. tostring(i - 1))
        phaseButton:SetScript("OnClick", function(self, button, down) gearList(classInfo.bisItems[i - 1])  end)
        if i == 1 then
            phaseButton:SetPoint("TOPLEFT", classString, "TOPRIGHT", 12, 0)
        else
            phaseButton:SetPoint("TOPLEFT", phaseButtons[#phaseButtons], "TOPRIGHT", 12, 0)
        end
        phaseButtons[i] = phaseButton
    end

    item:SetSize(classString:GetWidth(), classString:GetHeight())
    item:SetPoint("TOPLEFT",12, -15)

    table.insert(bb.showedClassTitle, item)

    gearList(classInfo.bisItems[0])
end

local function classItem(class, spec, index)
    local classKey = class .. spec
    local c = class:upper()
    local color = RAID_CLASS_COLORS[c]
    local coords = CLASS_ICON_TCOORDS[c]
    local classIconString = "|T" .. iconPath .. ":14:14:::256:256:" .. iconOffset(coords[1] * 4, coords[3] * 4) .. "|t"

    -- Item
    local item = CreateFrame("Button", nil, bb.leftContainer, BackdropTemplateMixin and "BackdropTemplate")
    item:SetBackdrop({ bgFile = "", edgeFile = "", edgeSize = 0, insets = { left = 3, right = 3, top = 3, bottom = 3 } });
    item:SetBackdropColor(0,0,0,0)
    item:SetHighlightTexture("Interface\\QuestFrame\\UI-QuestLogTitleHighlight");
    item:GetHighlightTexture():SetVertexColor(0.1,0.22,0.35);
    item:SetScript("OnClick",
            function(self,button,down)
                itemsTitle(bb.items[classKey]);
            end)

    local classString = item:CreateFontString(nil,"ARTWORK","GameFontHighlight");
    classString:SetPoint("TOPLEFT", 2, 0)
    classString:SetFont(classString:GetFont(),16,"THICKOUTLINE");
    classString:SetText(classIconString .. " " .. class .. " " .. spec)
    classString:SetTextColor(color.r, color.g, color.b)

    item:SetSize(classString:GetWidth(), classString:GetHeight())

    if (index == 1) then
        item:SetPoint("TOPLEFT",12, -8)
    else
        item:SetPoint("TOPLEFT",bb.classItems[#bb.classItems], "BOTTOMLEFT", 0, -4)
    end

    bb.classItems[index] = item

end

--------------------------------------------------------------------------------------------------------
--                                           Generate Data                                            --
--------------------------------------------------------------------------------------------------------

local function buildClasses()
    local index = 1
    for _, classInfo in pairs(bb.items) do
        if index == 1 then
            itemsTitle(classInfo)
        end
        classItem(classInfo.class, classInfo.spec, index)
        index = index + 1
    end

end

local function OnShow()
    buildClasses()
end

local function OnHide()
    if #bb.showedClassTitle ~= 0 then
        bb.showedClassTitle[1]:Hide()
        wipe(bb.showedClassTitle)
    end
    wipe(bb.classItems)
    bb.selectedClass = {}

    collectgarbage()
end

-- Init Base UI
bb:SetSize(800, 600)
bb:SetPoint("CENTER")
bb:SetBackdrop({ bgFile = "Interface\\ChatFrame\\ChatFrameBackground", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", edgeSize = 16, insets = { left = 3, right = 3, top = 3, bottom = 3 } });
bb:SetBackdropColor(0.1,0.22,0.35,1);
bb:SetBackdropBorderColor(0.1,0.1,0.1,1);
bb:EnableMouse(true);
bb:SetMovable(true);
bb:SetToplevel(true);
bb:SetClampedToScreen(true);
bb:Hide();

bb:SetScript("OnShow",OnShow);
bb:SetScript("OnHide",OnHide);

bb.outline = CreateFrame("Frame",nil,bb,BackdropTemplateMixin and "BackdropTemplate");	-- 9.0.1: Using BackdropTemplate
bb.outline:SetBackdrop({ bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", edgeSize = 16, insets = { left = 4, right = 4, top = 4, bottom = 4 } });
bb.outline:SetBackdropColor(0.1,0.1,0.2,1);
bb.outline:SetBackdropBorderColor(0.8,0.8,0.9,0.4);
bb.outline:SetPoint("TOPLEFT",12,-38);
bb.outline:SetPoint("BOTTOMRIGHT",-324, 42);

bb.header = bb:CreateFontString(nil,"ARTWORK","GameFontHighlight");
bb.header:SetPoint("TOPLEFT",12,-12);
bb.header:SetFont(bb.header:GetFont(),16,"THICKOUTLINE");
bb.header:SetText('Best In Slot Browser')

bb.close = CreateFrame("Button",nil,bb,"UIPanelCloseButton");
bb.close:SetPoint("TOPRIGHT",-4,-4);
bb.close:SetScript("OnClick",function(self,button,down) bb:Hide(); end);

-- Container
bb.container = CreateFrame("Frame", nil, bb, BackdropTemplateMixin and "BackdropTemplate")
bb.container:SetBackdrop({ bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", edgeSize = 16, insets = { left = 6, right = 6, top = 6, bottom = 6 } });
bb.container:SetPoint("TOPLEFT", 12, -38);
bb.container:SetPoint("BOTTOMRIGHT", -324, 42);
bb.container:SetBackdropColor(0.1,0.1,0.2,1);

-- Class List
bb.leftContainer = CreateFrame("Frame", nil, bb, BackdropTemplateMixin and "BackdropTemplate")
bb.leftContainer:SetBackdrop({ bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", edgeFile = "Interface\\Tooltips\\UI-Tooltip-Border", edgeSize = 16, insets = { left = 6, right = 6, top = 6, bottom = 6 } });
bb.leftContainer:SetPoint("TOPLEFT", bb.container, "TOPRIGHT", 12, 0);
bb.leftContainer:SetPoint("BOTTOMRIGHT", -12, 42);
bb.leftContainer:SetBackdropColor(0.1,0.1,0.2,1);

bb.footer = bb:CreateFontString(nil,"ARTWORK","GameFontHighlight");
bb.footer:SetPoint("BOTTOMRIGHT",-12,12);
bb.footer:SetFont(bb.footer:GetFont(),10,"THICKOUTLINE");
bb.footer:SetText('Powered by zesming, a.k.a 明子 @辛洛斯 - 娱乐夜不眠')
bb.footer:SetTextColor(1, 1, 1, 0.5)

_G["SLASH_".."BB".."1"] = "/bb";
_G["SLASH_".."BB".."2"] = "/ybm";
SlashCmdList["BB"] = function(cmd)
    -- Show/Hide Dialog
    bb:SetShown(not bb:IsVisible());
end

function bb:RegisterItem(bisEntry, ID, slot, description, phase)
    local classKey = bisEntry.class..bisEntry.spec

    if not bb.items[classKey] then
        bb.items[classKey] = {
            class = bisEntry.class,
            spec = bisEntry.spec,
            bisItems = {}
        }
    end

    if not bb.items[classKey].bisItems[phase] then
        bb.items[classKey].bisItems[phase] = {}
    end

    local itemInfo = {
        ID = ID,
        slot = slot,
        desc = description
    }

    table.insert(bb.items[classKey].bisItems[phase], itemInfo)
end
