name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: release_${{ github.ref }}.zip
          path: './BestInSlot'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release_${{ github.ref }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}